# Generated by Django 5.0.6 on 2024-09-19 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_project_task_comment_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='project_id',
            new_name='project',
        ),
        migrations.AddField(
            model_name='task',
            name='stage',
            field=models.CharField(default='to-do', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.CharField(default='unassigned', max_length=100),
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_do', models.IntegerField()),
                ('in_progress', models.IntegerField()),
                ('completed', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstone.project')),
            ],
        ),
    ]
