# Generated by Django 5.0.6 on 2024-09-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_rename_task_id_comment_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='in_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='team_leader',
            field=models.CharField(default='unassigned', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='to_do',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Tracker',
        ),
    ]
