# Generated by Django 5.0.6 on 2024-09-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_project_completed_project_in_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comment_number',
            field=models.IntegerField(default=0),
        ),
    ]
