# Generated by Django 5.0.6 on 2024-09-28 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_task_comment_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='txt',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='txt',
            new_name='task',
        ),
    ]
