# Generated by Django 5.0.6 on 2024-10-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0006_rename_txt_comment_comment_rename_txt_task_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='comment_number',
            new_name='comment_count',
        ),
    ]
