# Generated by Django 5.1.2 on 2024-10-16 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0007_rename_comment_number_task_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='project',
            name='in_progress',
        ),
        migrations.RemoveField(
            model_name='project',
            name='to_do',
        ),
    ]
